# Generated by Django 5.1.1 on 2024-11-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_comic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trade_images/'),
        ),
    ]
