# Generated by Django 5.1.1 on 2024-12-02 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0004_tradeoffer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
