# Generated by Django 5.1.1 on 2024-12-02 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_tradeoffer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 2, 3, 51, 19, 374294, tzinfo=datetime.timezone.utc)),
        ),
    ]
