# Generated by Django 5.1.1 on 2024-12-02 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0007_alter_tradeoffer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
